### ISSUE TITLE
[Feat] #1 - 메인 BottomSheet 구현

### ISSUE THREAD

**Issue by cjs1399** [MY-SOPT-IN/MY-SOPT-IN-iOS#8]
## 🛠 Issue
메인화면 BottomSheet 구현 

## 📝 To-do

- [ ] BottomSheet UI Components 지정 및 Layout
- [ ] 수정하기, 월별 통계 보기 뷰 연결
- [ ] 전체 삭제하기 Custom Alert 구현
